-- MySQL Script generated by MySQL Workbench
-- 10/18/17 01:52:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema teatrdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teatrdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teatrdb` DEFAULT CHARACTER SET utf8 ;
USE `teatrdb` ;

-- -----------------------------------------------------
-- Table `teatrdb`.`mesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teatrdb`.`mesto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ryad` INT(11) NULL DEFAULT NULL,
  `number` INT(11) NULL DEFAULT NULL,
  `cost` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teatrdb`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teatrdb`.`person` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `pass` VARCHAR(45) NULL DEFAULT NULL,
  `persontype` VARCHAR(45) NULL DEFAULT NULL,
  `cash` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teatrdb`.`spectacle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teatrdb`.`spectacle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cost` INT(11) NULL DEFAULT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `info` VARCHAR(500) NULL DEFAULT NULL,
  `spectaclestatus` VARCHAR(45) NULL DEFAULT NULL,
  `kinkompid` INT(11) NULL DEFAULT NULL,
  `time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_spectacle_to_person_idx` (`kinkompid` ASC),
  CONSTRAINT `fk_spectacle_to_person`
    FOREIGN KEY (`kinkompid`)
    REFERENCES `teatrdb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teatrdb`.`seans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teatrdb`.`seans` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `spectacleid` INT(11) NOT NULL,
  `timestart` TIMESTAMP NULL DEFAULT NULL,
  `timeend` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seans_to_spectacle_idx` (`spectacleid` ASC),
  CONSTRAINT `fk_seans_to_spectacle`
    FOREIGN KEY (`spectacleid`)
    REFERENCES `teatrdb`.`spectacle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teatrdb`.`bron`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teatrdb`.`bron` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bronstatus` VARCHAR(45) NULL DEFAULT NULL,
  `clientid` INT(11) NULL DEFAULT NULL,
  `seansid` INT(11) NULL DEFAULT NULL,
  `mestoid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_br_to_person_idx` (`clientid` ASC),
  INDEX `fk_br_to_seans_idx` (`seansid` ASC),
  INDEX `fk_br_to_mesto_idx` (`mestoid` ASC),
  CONSTRAINT `fk_br_to_mesto`
    FOREIGN KEY (`mestoid`)
    REFERENCES `teatrdb`.`mesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_br_to_person`
    FOREIGN KEY (`clientid`)
    REFERENCES `teatrdb`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_br_to_seans`
    FOREIGN KEY (`seansid`)
    REFERENCES `teatrdb`.`seans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
